# Generated by Django 6.0.8 on 2026-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Allow this staff member to delete customers, products and categories.'),
        ),
    ]
